name: Commit Terminus

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Installing PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: '7.3'
    - name: Installing Terminus
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    - name: update files
      if: success()
      run: terminus import:files botvietbai.dev https://dev-botvietbai.pantheonsite.io/test.zip --yes

    - name: commit the changed
      if: success()
      run: terminus env:commit --message "updated" --force -- botvietbai.dev
